-- == LICENSE =================================================================
-- The MIT License (MIT)
--
-- Copyright (c) 2014 - 2018 Peter Melnichenko
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in all
-- copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-- SOFTWARE.
--
-- Current Factorio Version 2.0.39, luacheck version 1.1.1

-- == CONFIG ==================================================================

local mod_name = 'fsrc'
local LIB = mod_name .. '_lib'
local LIB_DATA = LIB .. '_data'
local LIB_CONTROL = LIB .. '_control'
local RULES = 'lua52c+factorio+' .. LIB
local DATA_RULES = 'lua52c+factorio+factorio_data+' .. LIB .. '+' .. LIB_DATA
local CONTROL_RULES = 'lua52c+factorio+factorio_control+' .. LIB .. '+' .. LIB_CONTROL

-- == LUACHECK SETTINGS =======================================================

-- String or set of standard globals
std = RULES

-- Array of strings or field definition map
globals = { mod_name, '_DEBUG' }

-- Number or false
max_line_length = false

-- Array of strings
not_globals = { 'coroutine', 'io', 'socket', 'dofile', 'loadfile' }

-- Array of patterns (see Patterns)
ignore = { '21./%w+_$', '21./^_%w+$', '213/[ijk]', '213/index', '213/key', '58[1-2]' }

-- Integer in range 0..3
quiet = 1 -- pass -q option

-- Number or false
max_cyclomatic_complexity = 75

-- Boolean
codes = true

--Array of strings, list of files and directories to exclude
exclude_files = {
    '**/.*/*', --Ignore paths that start with .
}

-- == RULESETS ================================================================

files['**/utils/'].std = RULES

files['**/data.lua'].std = DATA_RULES
files['**/data-updates.lua'].std = DATA_RULES
files['**/data-final-fixes.lua'].std = DATA_RULES
files['**/settings.lua'].std = DATA_RULES
files['**/settings-updates.lua'].std = DATA_RULES
files['**/settings-final-fixes.lua'].std = DATA_RULES
files['**/prototypes/'].std = DATA_RULES
files['**/settings/'].std = DATA_RULES

files['**/scripts/'].std = CONTROL_RULES
files['**/control.lua'].std = CONTROL_RULES
files['**/utils/containers/'].std = CONTROL_RULES
files['**/utils/event-core.lua'].std = CONTROL_RULES
files['**/utils/event.lua'].std = CONTROL_RULES
files['**/utils/gui.lua'].std = CONTROL_RULES
files['**/utils/storage.lua'].std = CONTROL_RULES
files['**/utils/task.lua'].std = CONTROL_RULES
files['**/utils/token.lua'].std = CONTROL_RULES

-- == MOD LIB =================================================================

stds[LIB] = {
    read_globals = {
        string = {
            other_fields = false,
            fields = {
                'starts_with',
                'ends_with',
                'contains',
                'replace',
                'msv',
                'find_base',
                'trim',
                'capital_letter',
            },
        },
        table = {
            other_fields = false,
            fields = {
                'remove_element',
                'remove_any',
                'fast_remove',
                'add_all',
                'index_of',
                'index_of_in_array',
                'contains',
                'array_contains',
                'set',
                'keys',
                'get_random_dictionary_entry',
                'get_random_weighted',
                'get_random_weighted_chances',
                'shuffle_table',
                'clear_table',
                'binary_search',
                'size',
                'merge',
                'equals',
            },
        },
        math = {
            other_fields = false,
            fields = {
                'sqrt2',
                'inv_sqrt2',
                'tau',
                'round_sin',
                'round_cos',
                'round',
                'round_sig',
                'clamp',
                'calculate_slope',
                'calculate_y_intercept',
                'degrees',
                'mean',
                'median',
                'mode',
                'standard_deviation',
                'range',
            },
        },
    },
}

stds[LIB_DATA] = {}

stds[LIB_CONTROL] = {
    read_globals = {
        defines = {
            other_fields = false,
            fields = {
                events = {
                    other_fields = false,
                    fields = {
                        'on_map_init',
                        'on_map_reset',
                        'on_match_started',
                        'on_match_finished',
                        'on_match_picking_phase',
                        'on_match_preparation_phase',
                        'on_challenges_changed',
                    }
                }
            }
        }
    }
}

-- == FACTORIO ================================================================

stds.factorio = {
    read_globals = {
        'log',
        'localised_print',
        'serpent',
        'table_size',
        table = {
            other_fields = false,
            fields = {
                'compare',
                'deepcopy',
            },
        },
        util = {
            other_fields = false,
            fields = {
                'add_shift_offset',
                'add_shift',
                'by_pixel_hr',
                'by_pixel',
                'clamp',
                'color',
                'combine_icons',
                'conditional_return',
                'distance',
                'draw_as_glow',
                'empty_animation',
                'empty_icon',
                'empty_sprite',
                'foreach_sprite_definition',
                'format_number',
                'formattime',
                'get_color_with_alpha',
                'get_recipe_main_product',
                'get_walkable_tile',
                'increment',
                'insert_safe',
                'list_to_map',
                'merge',
                'mix_color',
                'moveposition',
                'mul_shift',
                'multiply_color',
                'multiplystripes',
                'normalize_recipe_product',
                'normalize_recipe_products',
                'oppositedirection',
                'parse_energy',
                'positiontostr',
                'premul_color',
                'product_amount',
                'remove_from_list',
                'remove_safe',
                'remove_tile_references',
                'rotate_position',
                'split_whitespace',
                'split',
                'sprite_load',
                'spritesheets_to_pictures',
                'string_replace',
                'string_starts_with',
                'technology_icon_constant_braking_force',
                'technology_icon_constant_capacity',
                'technology_icon_constant_damage',
                'technology_icon_constant_equipment',
                'technology_icon_constant_followers',
                'technology_icon_constant_mining',
                'technology_icon_constant_movement_speed',
                'technology_icon_constant_planet',
                'technology_icon_constant_productivity',
                'technology_icon_constant_range',
                'technology_icon_constant_recipe_productivity',
                'technology_icon_constant_speed',
                'technology_icon_constant_stack_size',
            },
        },
        defines = {
            other_fields = false,
            read_only = true,
            fields = {
                alert_type = {
                    other_fields = false,
                    fields = {
                        'collector_path_blocked',
                        'custom',
                        'entity_destroyed',
                        'entity_under_attack',
                        'no_material_for_construction',
                        'no_platform_storage',
                        'no_roboport_storage',
                        'no_storage',
                        'not_enough_construction_robots',
                        'not_enough_repair_packs',
                        'pipeline_overextended',
                        'platform_tile_building_blocked',
                        'train_no_path',
                        'train_out_of_fuel',
                        'turret_fire',
                        'turret_out_of_ammo',
                        'unclaimed_cargo',
                    },
                },
                behavior_result = {
                    other_fields = false,
                    fields = {
                        'deleted',
                        'fail',
                        'in_progress',
                        'success',
                    },
                },
                build_check_type = {
                    other_fields = false,
                    fields = {
                        'blueprint_ghost',
                        'ghost_revive',
                        'manual',
                        'manual_ghost',
                        'script',
                        'script_ghost',
                    },
                },
                build_mode = {
                    other_fields = false,
                    fields = {
                        'forced',
                        'normal',
                        'superforced',
                    },
                },
                cargo_destination = {
                    other_fields = false,
                    fields = {
                        'invalid',
                        'orbit',
                        'space_platform',
                        'station',
                        'surface',
                    },
                },
                chain_signal_state = {
                    other_fields = false,
                    fields = {
                        'all_open',
                        'none',
                        'none_open',
                        'partially_open',
                    },
                },
                chunk_generated_status = {
                    other_fields = false,
                    fields = {
                        'basic_tiles',
                        'corrected_tiles',
                        'custom_tiles',
                        'entities',
                        'nothing',
                        'tiles',
                    },
                },
                command = {
                    other_fields = false,
                    fields = {
                        'attack',
                        'attack_area',
                        'build_base',
                        'compound',
                        'flee',
                        'go_to_location',
                        'group',
                        'stop',
                        'wander',
                    },
                },
                compound_command = {
                    other_fields = false,
                    fields = {
                        'logical_and',
                        'logical_or',
                        'return_last',
                    },
                },
                control_behavior = {
                    other_fields = false,
                    fields = {
                        cargo_landing_pad = {
                            other_fields = false,
                            fields = {
                                exclusive_mode = {
                                    other_fields = false,
                                    fields = {
                                        'none',
                                        'send_contents',
                                        'set_requests',
                                    },
                                },
                            },
                        },
                        inserter = {
                            other_fields = false,
                            fields = {
                                hand_read_mode = {
                                    other_fields = false,
                                    fields = {
                                        'hold',
                                        'pulse',
                                    },
                                },
                            },
                        },
                        lamp = {
                            other_fields = false,
                            fields = {
                                color_mode = {
                                    other_fields = false,
                                    fields = {
                                        'color_mapping',
                                        'components',
                                        'packed_rgb',
                                    },
                                },
                            },
                        },
                        logistic_container = {
                            other_fields = false,
                            fields = {
                                exclusive_mode = {
                                    other_fields = false,
                                    fields = {
                                        'none',
                                        'send_contents',
                                        'set_requests',
                                    },
                                },
                            },
                        },
                        mining_drill = {
                            other_fields = false,
                            fields = {
                                resource_read_mode = {
                                    other_fields = false,
                                    fields = {
                                        'entire_patch',
                                        'this_miner',
                                    },
                                },
                            },
                        },
                        roboport = {
                            other_fields = false,
                            fields = {
                                read_items_mode = {
                                    other_fields = false,
                                    fields = {
                                        'logistics',
                                        'missing_requests',
                                        'none',
                                    },
                                },
                            },
                        },
                        rocket_silo = {
                            other_fields = false,
                            fields = {
                                read_mode = {
                                    other_fields = false,
                                    fields = {
                                        'logistic_inventory',
                                        'none',
                                        'orbital_requests',
                                    },
                                },
                            },
                        },
                        transport_belt = {
                            other_fields = false,
                            fields = {
                                content_read_mode = {
                                    other_fields = false,
                                    fields = {
                                        'entire_belt_hold',
                                        'hold',
                                        'pulse',
                                    },
                                },
                            },
                        },
                        type = {
                            other_fields = false,
                            fields = {
                                'accumulator',
                                'agricultural_tower',
                                'arithmetic_combinator',
                                'artillery_turret',
                                'assembling_machine',
                                'asteroid_collector',
                                'cargo_landing_pad',
                                'constant_combinator',
                                'container',
                                'decider_combinator',
                                'display_panel',
                                'generic_on_off',
                                'inserter',
                                'lamp',
                                'loader',
                                'logistic_container',
                                'mining_drill',
                                'programmable_speaker',
                                'pump',
                                'radar',
                                'rail_chain_signal',
                                'rail_signal',
                                'reactor',
                                'roboport',
                                'rocket_silo',
                                'selector_combinator',
                                'space_platform_hub',
                                'storage_tank',
                                'train_stop',
                                'transport_belt',
                                'turret',
                                'wall',
                            },
                        },
                    },
                },
                controllers = {
                    other_fields = false,
                    fields = {
                        'character',
                        'cutscene',
                        'editor',
                        'ghost',
                        'god',
                        'remote',
                        'spectator',
                    },
                },
                deconstruction_item = {
                    other_fields = false,
                    fields = {
                        entity_filter_mode = {
                            other_fields = false,
                            fields = {
                                'blacklist',
                                'whitelist',
                            },
                        },
                        tile_filter_mode = {
                            other_fields = false,
                            fields = {
                                'blacklist',
                                'whitelist',
                            },
                        },
                        tile_selection_mode = {
                            other_fields = false,
                            fields = {
                                'always',
                                'never',
                                'normal',
                                'only',
                            },
                        },
                    },
                },
                'default_icon_size',
                difficulty = {
                    other_fields = false,
                    fields = {
                        'easy',
                        'hard',
                        'normal',
                    },
                },
                direction = {
                    other_fields = false,
                    fields = {
                        'east',
                        'eastnortheast',
                        'eastsoutheast',
                        'north',
                        'northeast',
                        'northnortheast',
                        'northnorthwest',
                        'northwest',
                        'south',
                        'southeast',
                        'southsoutheast',
                        'southsouthwest',
                        'southwest',
                        'west',
                        'westnorthwest',
                        'westsouthwest',
                    },
                },
                disconnect_reason = {
                    other_fields = false,
                    fields = {
                        'afk',
                        'banned',
                        'cannot_keep_up',
                        'desync_limit_reached',
                        'dropped',
                        'kicked',
                        'kicked_and_deleted',
                        'quit',
                        'reconnect',
                        'switching_servers',
                        'wrong_input',
                    },
                },
                distraction = {
                    other_fields = false,
                    fields = {
                        'by_anything',
                        'by_damage',
                        'by_enemy',
                        'none',
                    },
                },
                entity_status = {
                    other_fields = false,
                    fields = {
                        'broken',
                        'cant_divide_segments',
                        'charging',
                        'closed_by_circuit_network',
                        'computing_navigation',
                        'destination_stop_full',
                        'disabled',
                        'disabled_by_control_behavior',
                        'disabled_by_script',
                        'discharging',
                        'fluid_ingredient_shortage',
                        'frozen',
                        'full_burnt_result_output',
                        'full_output',
                        'fully_charged',
                        'ghost',
                        'item_ingredient_shortage',
                        'launching_rocket',
                        'low_input_fluid',
                        'low_power',
                        'low_temperature',
                        'marked_for_deconstruction',
                        'missing_required_fluid',
                        'missing_science_packs',
                        'networks_connected',
                        'networks_disconnected',
                        'no_ammo',
                        'no_filter',
                        'no_fuel',
                        'no_ingredients',
                        'no_input_fluid',
                        'no_minable_resources',
                        'no_modules_to_transmit',
                        'no_path',
                        'no_power',
                        'no_recipe',
                        'no_research_in_progress',
                        'no_spot_seedable_by_inputs',
                        'normal',
                        'not_connected_to_hub_or_pad',
                        'not_connected_to_rail',
                        'not_enough_space_in_output',
                        'not_enough_thrust',
                        'not_plugged_in_electric_network',
                        'on_the_way',
                        'opened_by_circuit_network',
                        'out_of_logistic_network',
                        'paused',
                        'pipeline_overextended',
                        'preparing_rocket_for_launch',
                        'recharging_after_power_outage',
                        'recipe_not_researched',
                        'thrust_not_required',
                        'turned_off_during_daytime',
                        'waiting_at_stop',
                        'waiting_for_more_items',
                        'waiting_for_plants_to_grow',
                        'waiting_for_rockets_to_arrive',
                        'waiting_for_source_items',
                        'waiting_for_space_in_destination',
                        'waiting_for_space_in_platform_hub',
                        'waiting_for_target_to_be_built',
                        'waiting_for_train',
                        'waiting_in_orbit',
                        'waiting_to_launch_rocket',
                        'working',
                    },
                },
                entity_status_diode = {
                    other_fields = false,
                    fields = {
                        'green',
                        'red',
                        'yellow',
                    },
                },
                events = {
                    other_fields = false,
                    fields = {
                        'crash-site-skip-cutscene',
                        'give-artillery-targeting-remote',
                        'give-blueprint-book',
                        'give-blueprint',
                        'give-copper-wire',
                        'give-deconstruction-planner',
                        'give-discharge-defense-remote',
                        'give-green-wire',
                        'give-red-wire',
                        'give-spidertron-remote',
                        'give-upgrade-planner',
                        'on_achievement_gained',
                        'on_ai_command_completed',
                        'on_area_cloned',
                        'on_biter_base_built',
                        'on_brush_cloned',
                        'on_build_base_arrived',
                        'on_built_entity',
                        'on_cancelled_deconstruction',
                        'on_cancelled_upgrade',
                        'on_cargo_pod_delivered_cargo',
                        'on_cargo_pod_finished_ascending',
                        'on_cargo_pod_finished_descending',
                        'on_character_corpse_expired',
                        'on_chart_tag_added',
                        'on_chart_tag_modified',
                        'on_chart_tag_removed',
                        'on_chunk_charted',
                        'on_chunk_deleted',
                        'on_chunk_generated',
                        'on_combat_robot_expired',
                        'on_console_chat',
                        'on_console_command',
                        'on_cutscene_cancelled',
                        'on_cutscene_finished',
                        'on_cutscene_started',
                        'on_cutscene_waypoint_reached',
                        'on_entity_cloned',
                        'on_entity_color_changed',
                        'on_entity_damaged',
                        'on_entity_died',
                        'on_entity_logistic_slot_changed',
                        'on_entity_renamed',
                        'on_entity_settings_pasted',
                        'on_entity_spawned',
                        'on_equipment_inserted',
                        'on_equipment_removed',
                        'on_force_cease_fire_changed',
                        'on_force_created',
                        'on_force_friends_changed',
                        'on_force_reset',
                        'on_forces_merged',
                        'on_forces_merging',
                        'on_game_created_from_scenario',
                        'on_gui_checked_state_changed',
                        'on_gui_click',
                        'on_gui_closed',
                        'on_gui_confirmed',
                        'on_gui_elem_changed',
                        'on_gui_hover',
                        'on_gui_leave',
                        'on_gui_location_changed',
                        'on_gui_opened',
                        'on_gui_selected_tab_changed',
                        'on_gui_selection_state_changed',
                        'on_gui_switch_state_changed',
                        'on_gui_text_changed',
                        'on_gui_value_changed',
                        'on_land_mine_armed',
                        'on_lua_shortcut',
                        'on_marked_for_deconstruction',
                        'on_marked_for_upgrade',
                        'on_market_item_purchased',
                        'on_mod_item_opened',
                        'on_multiplayer_init',
                        'on_object_destroyed',
                        'on_permission_group_added',
                        'on_permission_group_deleted',
                        'on_permission_group_edited',
                        'on_permission_string_imported',
                        'on_picked_up_item',
                        'on_player_alt_reverse_selected_area',
                        'on_player_alt_selected_area',
                        'on_player_ammo_inventory_changed',
                        'on_player_armor_inventory_changed',
                        'on_player_banned',
                        'on_player_built_tile',
                        'on_player_cancelled_crafting',
                        'on_player_changed_force',
                        'on_player_changed_position',
                        'on_player_changed_surface',
                        'on_player_cheat_mode_disabled',
                        'on_player_cheat_mode_enabled',
                        'on_player_clicked_gps_tag',
                        'on_player_configured_blueprint',
                        'on_player_controller_changed',
                        'on_player_crafted_item',
                        'on_player_created',
                        'on_player_cursor_stack_changed',
                        'on_player_deconstructed_area',
                        'on_player_demoted',
                        'on_player_died',
                        'on_player_display_density_scale_changed',
                        'on_player_display_resolution_changed',
                        'on_player_display_scale_changed',
                        'on_player_driving_changed_state',
                        'on_player_dropped_item',
                        'on_player_fast_transferred',
                        'on_player_flipped_entity',
                        'on_player_flushed_fluid',
                        'on_player_gun_inventory_changed',
                        'on_player_input_method_changed',
                        'on_player_joined_game',
                        'on_player_kicked',
                        'on_player_left_game',
                        'on_player_locale_changed',
                        'on_player_main_inventory_changed',
                        'on_player_mined_entity',
                        'on_player_mined_item',
                        'on_player_mined_tile',
                        'on_player_muted',
                        'on_player_pipette',
                        'on_player_placed_equipment',
                        'on_player_promoted',
                        'on_player_removed_equipment',
                        'on_player_removed',
                        'on_player_repaired_entity',
                        'on_player_respawned',
                        'on_player_reverse_selected_area',
                        'on_player_rotated_entity',
                        'on_player_selected_area',
                        'on_player_set_quick_bar_slot',
                        'on_player_setup_blueprint',
                        'on_player_toggled_alt_mode',
                        'on_player_toggled_map_editor',
                        'on_player_trash_inventory_changed',
                        'on_player_unbanned',
                        'on_player_unmuted',
                        'on_player_used_capsule',
                        'on_player_used_spidertron_remote',
                        'on_post_entity_died',
                        'on_pre_build',
                        'on_pre_chunk_deleted',
                        'on_pre_entity_settings_pasted',
                        'on_pre_ghost_deconstructed',
                        'on_pre_ghost_upgraded',
                        'on_pre_permission_group_deleted',
                        'on_pre_permission_string_imported',
                        'on_pre_player_crafted_item',
                        'on_pre_player_died',
                        'on_pre_player_left_game',
                        'on_pre_player_mined_item',
                        'on_pre_player_removed',
                        'on_pre_player_toggled_map_editor',
                        'on_pre_robot_exploded_cliff',
                        'on_pre_scenario_finished',
                        'on_pre_script_inventory_resized',
                        'on_pre_surface_cleared',
                        'on_pre_surface_deleted',
                        'on_redo_applied',
                        'on_research_cancelled',
                        'on_research_finished',
                        'on_research_moved',
                        'on_research_reversed',
                        'on_research_started',
                        'on_resource_depleted',
                        'on_robot_built_entity',
                        'on_robot_built_tile',
                        'on_robot_exploded_cliff',
                        'on_robot_mined_entity',
                        'on_robot_mined_tile',
                        'on_robot_mined',
                        'on_robot_pre_mined',
                        'on_rocket_launch_ordered',
                        'on_rocket_launched',
                        'on_runtime_mod_setting_changed',
                        'on_script_inventory_resized',
                        'on_script_path_request_finished',
                        'on_script_trigger_effect',
                        'on_sector_scanned',
                        'on_segment_entity_created',
                        'on_selected_entity_changed',
                        'on_singleplayer_init',
                        'on_space_platform_built_entity',
                        'on_space_platform_built_tile',
                        'on_space_platform_changed_state',
                        'on_space_platform_mined_entity',
                        'on_space_platform_mined_item',
                        'on_space_platform_mined_tile',
                        'on_space_platform_pre_mined',
                        'on_spider_command_completed',
                        'on_string_translated',
                        'on_surface_cleared',
                        'on_surface_created',
                        'on_surface_deleted',
                        'on_surface_imported',
                        'on_surface_renamed',
                        'on_technology_effects_reset',
                        'on_tick',
                        'on_train_changed_state',
                        'on_train_created',
                        'on_train_schedule_changed',
                        'on_trigger_created_entity',
                        'on_trigger_fired_artillery',
                        'on_undo_applied',
                        'on_unit_added_to_group',
                        'on_unit_group_created',
                        'on_unit_group_finished_gathering',
                        'on_unit_removed_from_group',
                        'on_worker_robot_expired',
                        'script_raised_built',
                        'script_raised_destroy',
                        'script_raised_revive',
                        'script_raised_set_tiles',
                        'script_raised_teleported',
                        'toggle-equipment-movement-bonus',
                        'toggle-personal-logistic-requests',
                        'toggle-personal-roboport',
                    },
                },
                flow_precision_index = {
                    other_fields = false,
                    fields = {
                        'fifty_hours',
                        'five_seconds',
                        'one_hour',
                        'one_minute',
                        'one_thousand_hours',
                        'ten_hours',
                        'ten_minutes',
                        'two_hundred_fifty_hours',
                    },
                },
                game_controller_interaction = {
                    other_fields = false,
                    fields = {
                        'always',
                        'never',
                        'normal',
                    },
                },
                group_state = {
                    other_fields = false,
                    fields = {
                        'attacking_distraction',
                        'attacking_target',
                        'finished',
                        'gathering',
                        'moving',
                        'pathfinding',
                        'wander_in_group',
                    },
                },
                gui_type = {
                    other_fields = false,
                    fields = {
                        'achievement',
                        'blueprint_library',
                        'bonus',
                        'controller',
                        'custom',
                        'entity',
                        'equipment',
                        'global_electric_network',
                        'item',
                        'logistic',
                        'none',
                        'opened_entity_grid',
                        'other_player',
                        'permissions',
                        'player_management',
                        'production',
                        'script_inventory',
                        'server_management',
                        'tile',
                        'trains',
                    },
                },
                input_action = {
                    other_fields = false,
                    fields = {
                        'activate_interrupt',
                        'activate_paste',
                        'add_decider_combinator_condition',
                        'add_decider_combinator_output',
                        'add_logistic_section',
                        'add_permission_group',
                        'add_pin',
                        'add_train_interrupt',
                        'add_train_station',
                        'adjust_blueprint_snapping',
                        'admin_action',
                        'alt_reverse_select_area',
                        'alt_select_area',
                        'alt_select_blueprint_entities',
                        'alternative_copy',
                        'begin_mining',
                        'begin_mining_terrain',
                        'build',
                        'build_rail',
                        'build_terrain',
                        'cancel_craft',
                        'cancel_deconstruct',
                        'cancel_delete_space_platform',
                        'cancel_new_blueprint',
                        'cancel_research',
                        'cancel_upgrade',
                        'change_active_character_tab',
                        'change_active_item_group_for_crafting',
                        'change_active_item_group_for_filters',
                        'change_active_quick_bar',
                        'change_arithmetic_combinator_parameters',
                        'change_entity_label',
                        'change_item_label',
                        'change_logistic_point_group',
                        'change_multiplayer_config',
                        'change_picking_state',
                        'change_programmable_speaker_alert_parameters',
                        'change_programmable_speaker_circuit_parameters',
                        'change_programmable_speaker_parameters',
                        'change_riding_state',
                        'change_selector_combinator_parameters',
                        'change_shooting_state',
                        'change_train_name',
                        'change_train_stop_station',
                        'change_train_wait_condition',
                        'change_train_wait_condition_data',
                        'clear_cursor',
                        'connect_rolling_stock',
                        'copy',
                        'copy_entity_settings',
                        'copy_large_opened_blueprint',
                        'copy_large_opened_item',
                        'copy_opened_blueprint',
                        'copy_opened_item',
                        'craft',
                        'create_space_platform',
                        'cursor_direction',
                        'cursor_split',
                        'cursor_transfer',
                        'custom_input',
                        'cycle_blueprint_book_backwards',
                        'cycle_blueprint_book_forwards',
                        'cycle_quality_down',
                        'cycle_quality_up',
                        'deconstruct',
                        'delete_blueprint_library',
                        'delete_blueprint_record',
                        'delete_custom_tag',
                        'delete_logistic_group',
                        'delete_permission_group',
                        'delete_space_platform',
                        'destroy_item',
                        'destroy_opened_item',
                        'disconnect_rolling_stock',
                        'drag_decider_combinator_condition',
                        'drag_decider_combinator_output',
                        'drag_train_schedule',
                        'drag_train_schedule_interrupt',
                        'drag_train_wait_condition',
                        'drop_blueprint_record',
                        'drop_item',
                        'edit_blueprint_tool_preview',
                        'edit_custom_tag',
                        'edit_display_panel',
                        'edit_display_panel_always_show',
                        'edit_display_panel_icon',
                        'edit_display_panel_parameters',
                        'edit_display_panel_show_in_chart',
                        'edit_interrupt',
                        'edit_permission_group',
                        'edit_pin',
                        'enable_transitional_requests',
                        'export_blueprint',
                        'fast_entity_split',
                        'fast_entity_transfer',
                        'flip_entity',
                        'flush_opened_entity_fluid',
                        'flush_opened_entity_specific_fluid',
                        'go_to_train_station',
                        'grab_blueprint_record',
                        'gui_checked_state_changed',
                        'gui_click',
                        'gui_confirmed',
                        'gui_elem_changed',
                        'gui_hover',
                        'gui_leave',
                        'gui_location_changed',
                        'gui_selected_tab_changed',
                        'gui_selection_state_changed',
                        'gui_switch_state_changed',
                        'gui_text_changed',
                        'gui_value_changed',
                        'import_blueprint',
                        'import_blueprint_string',
                        'import_blueprints_filtered',
                        'import_permissions_string',
                        'instantly_create_space_platform',
                        'inventory_split',
                        'inventory_transfer',
                        'land_at_planet',
                        'launch_rocket',
                        'lua_shortcut',
                        'map_editor_action',
                        'market_offer',
                        'mod_settings_changed',
                        'modify_decider_combinator_condition',
                        'modify_decider_combinator_output',
                        'move_research',
                        'open_achievements_gui',
                        'open_blueprint_library_gui',
                        'open_blueprint_record',
                        'open_bonus_gui',
                        'open_character_gui',
                        'open_current_vehicle_gui',
                        'open_equipment',
                        'open_global_electric_network_gui',
                        'open_gui',
                        'open_item',
                        'open_logistics_gui',
                        'open_mod_item',
                        'open_new_platform_button_from_rocket_silo',
                        'open_opened_entity_grid',
                        'open_parent_of_opened_item',
                        'open_production_gui',
                        'open_train_gui',
                        'open_train_station_gui',
                        'open_trains_gui',
                        'parametrise_blueprint',
                        'paste_entity_settings',
                        'pin_alert_group',
                        'pin_custom_alert',
                        'pin_search_result',
                        'pipette',
                        'place_equipment',
                        'quick_bar_pick_slot',
                        'quick_bar_set_selected_page',
                        'quick_bar_set_slot',
                        'reassign_blueprint',
                        'redo',
                        'remote_view_entity',
                        'remote_view_surface',
                        'remove_cables',
                        'remove_decider_combinator_condition',
                        'remove_decider_combinator_output',
                        'remove_logistic_section',
                        'remove_pin',
                        'remove_train_interrupt',
                        'remove_train_station',
                        'rename_interrupt',
                        'rename_space_platform',
                        'reorder_logistic_section',
                        'request_missing_construction_materials',
                        'reset_assembling_machine',
                        'reverse_select_area',
                        'rotate_entity',
                        'select_area',
                        'select_asteroid_chunk_slot',
                        'select_blueprint_entities',
                        'select_entity_filter_slot',
                        'select_entity_slot',
                        'select_item_filter',
                        'select_mapper_slot_from',
                        'select_mapper_slot_to',
                        'select_next_valid_gun',
                        'select_tile_slot',
                        'send_spidertron',
                        'send_stack_to_trash',
                        'send_stacks_to_trash',
                        'send_train_to_pin_target',
                        'set_behavior_mode',
                        'set_car_weapons_control',
                        'set_cheat_mode_quality',
                        'set_circuit_condition',
                        'set_circuit_mode_of_operation',
                        'set_combinator_description',
                        'set_copy_color_from_train_stop',
                        'set_deconstruction_item_tile_selection_mode',
                        'set_deconstruction_item_trees_and_rocks_only',
                        'set_entity_color',
                        'set_entity_energy_property',
                        'set_filter',
                        'set_ghost_cursor',
                        'set_heat_interface_mode',
                        'set_heat_interface_temperature',
                        'set_infinity_container_filter_item',
                        'set_infinity_container_remove_unfiltered_items',
                        'set_infinity_pipe_filter',
                        'set_inserter_max_stack_size',
                        'set_inventory_bar',
                        'set_lamp_always_on',
                        'set_linked_container_link_i_d',
                        'set_logistic_filter_item',
                        'set_logistic_network_name',
                        'set_logistic_section_active',
                        'set_player_color',
                        'set_pump_fluid_filter',
                        'set_request_from_buffers',
                        'set_research_finished_stops_game',
                        'set_rocket_silo_send_to_orbit_automated_mode',
                        'set_schedule_record_allow_unloading',
                        'set_signal',
                        'set_splitter_priority',
                        'set_spoil_priority',
                        'set_train_stop_priority',
                        'set_train_stopped',
                        'set_trains_limit',
                        'set_turret_ignore_unlisted',
                        'set_use_inserter_filters',
                        'set_vehicle_automatic_targeting_parameters',
                        'setup_assembling_machine',
                        'setup_blueprint',
                        'setup_single_blueprint_record',
                        'spawn_item',
                        'spectator_change_surface',
                        'stack_split',
                        'stack_transfer',
                        'start_repair',
                        'start_research',
                        'start_walking',
                        'stop_drag_build',
                        'swap_logistic_filter_items',
                        'switch_connect_to_logistic_network',
                        'switch_constant_combinator_state',
                        'switch_inserter_filter_mode_state',
                        'switch_loader_filter_mode',
                        'switch_mining_drill_filter_mode_state',
                        'switch_power_switch_state',
                        'take_equipment',
                        'toggle_artillery_auto_targeting',
                        'toggle_deconstruction_item_entity_filter_mode',
                        'toggle_deconstruction_item_tile_filter_mode',
                        'toggle_driving',
                        'toggle_enable_vehicle_logistics_while_moving',
                        'toggle_entity_logistic_requests',
                        'toggle_equipment_movement_bonus',
                        'toggle_map_editor',
                        'toggle_personal_logistic_requests',
                        'toggle_personal_roboport',
                        'toggle_selected_entity',
                        'toggle_show_entity_info',
                        'translate_string',
                        'trash_not_requested_items',
                        'undo',
                        'upgrade',
                        'upgrade_opened_blueprint_by_item',
                        'upgrade_opened_blueprint_by_record',
                        'use_item',
                        'wire_dragging',
                        'write_to_console',
                    },
                },
                input_method = {
                    other_fields = false,
                    fields = {
                        'game_controller',
                        'keyboard_and_mouse',
                    },
                },
                inventory = {
                    other_fields = false,
                    fields = {
                        'artillery_turret_ammo',
                        'artillery_wagon_ammo',
                        'assembling_machine_dump',
                        'assembling_machine_input',
                        'assembling_machine_modules',
                        'assembling_machine_output',
                        'assembling_machine_trash',
                        'beacon_modules',
                        'burnt_result',
                        'car_ammo',
                        'car_trash',
                        'car_trunk',
                        'cargo_landing_pad_main',
                        'cargo_landing_pad_trash',
                        'cargo_unit',
                        'cargo_wagon',
                        'character_ammo',
                        'character_armor',
                        'character_corpse',
                        'character_guns',
                        'character_main',
                        'character_trash',
                        'character_vehicle',
                        'chest',
                        'editor_ammo',
                        'editor_armor',
                        'editor_guns',
                        'editor_main',
                        'fuel',
                        'furnace_modules',
                        'furnace_result',
                        'furnace_source',
                        'furnace_trash',
                        'god_main',
                        'hub_main',
                        'hub_trash',
                        'item_main',
                        'lab_input',
                        'lab_modules',
                        'logistic_container_trash',
                        'mining_drill_modules',
                        'proxy_main',
                        'roboport_material',
                        'roboport_robot',
                        'robot_cargo',
                        'robot_repair',
                        'rocket_silo_input',
                        'rocket_silo_modules',
                        'rocket_silo_output',
                        'rocket_silo_rocket',
                        'rocket_silo_trash',
                        'spider_ammo',
                        'spider_trash',
                        'spider_trunk',
                        'turret_ammo',
                    },
                },
                logistic_member_index = {
                    other_fields = false,
                    fields = {
                        'character_provider',
                        'character_requester',
                        'character_storage',
                        'generic_on_off_behavior',
                        'logistic_container',
                        'spidertron_requester',
                        'vehicle_storage',
                    },
                },
                logistic_mode = {
                    other_fields = false,
                    fields = {
                        'active_provider',
                        'buffer',
                        'none',
                        'passive_provider',
                        'requester',
                        'storage',
                    },
                },
                logistic_section_type = {
                    other_fields = false,
                    fields = {
                        'circuit_controlled',
                        'manual',
                        'request_missing_materials_controlled',
                        'transitional_request_controlled',
                    },
                },
                mouse_button_type = {
                    other_fields = false,
                    fields = {
                        'left',
                        'middle',
                        'none',
                        'right',
                    },
                },
                moving_state = {
                    other_fields = false,
                    fields = {
                        'adaptive',
                        'moving',
                        'stale',
                        'stuck',
                    },
                },
                print_skip = {
                    other_fields = false,
                    fields = {
                        'if_redundant',
                        'if_visible',
                        'never',
                    },
                },
                print_sound = {
                    other_fields = false,
                    fields = {
                        'always',
                        'never',
                        'use_player_settings',
                    },
                },
                rail_connection_direction = {
                    other_fields = false,
                    fields = {
                        'left',
                        'none',
                        'right',
                        'straight',
                    },
                },
                rail_direction = {
                    other_fields = false,
                    fields = {
                        'back',
                        'front',
                    },
                },
                rail_layer = {
                    other_fields = false,
                    fields = {
                        'elevated',
                        'ground',
                    },
                },
                relative_gui_position = {
                    other_fields = false,
                    fields = {
                        'bottom',
                        'left',
                        'right',
                        'top',
                    },
                },
                relative_gui_type = {
                    other_fields = false,
                    fields = {
                        'accumulator_gui',
                        'achievement_gui',
                        'additional_entity_info_gui',
                        'admin_gui',
                        'agriculture_tower_gui',
                        'arithmetic_combinator_gui',
                        'armor_gui',
                        'assembling_machine_gui',
                        'assembling_machine_select_recipe_gui',
                        'asteroid_collector_gui',
                        'beacon_gui',
                        'blueprint_book_gui',
                        'blueprint_library_gui',
                        'blueprint_setup_gui',
                        'bonus_gui',
                        'burner_equipment_gui',
                        'car_gui',
                        'cargo_landing_pad_gui',
                        'constant_combinator_gui',
                        'container_gui',
                        'controller_gui',
                        'decider_combinator_gui',
                        'deconstruction_item_gui',
                        'display_panel_gui',
                        'electric_energy_interface_gui',
                        'electric_network_gui',
                        'entity_variations_gui',
                        'entity_with_energy_source_gui',
                        'equipment_grid_gui',
                        'furnace_gui',
                        'generic_on_off_entity_gui',
                        'ghost_picker_gui',
                        'global_electric_network_gui',
                        'heat_interface_gui',
                        'infinity_pipe_gui',
                        'inserter_gui',
                        'item_with_inventory_gui',
                        'lab_gui',
                        'lamp_gui',
                        'linked_container_gui',
                        'loader_gui',
                        'logistic_gui',
                        'market_gui',
                        'mining_drill_gui',
                        'other_player_gui',
                        'permissions_gui',
                        'pick_stop_gui',
                        'pipe_gui',
                        'power_switch_gui',
                        'production_gui',
                        'programmable_speaker_gui',
                        'pump_gui',
                        'rail_signal_base_gui',
                        'reactor_gui',
                        'resource_entity_gui',
                        'roboport_gui',
                        'rocket_silo_gui',
                        'script_inventory_gui',
                        'selector_combinator_gui',
                        'server_config_gui',
                        'space_platform_hub_gui',
                        'spider_vehicle_gui',
                        'splitter_gui',
                        'standalone_character_gui',
                        'storage_tank_gui',
                        'tile_variations_gui',
                        'tips_and_tricks_gui',
                        'train_gui',
                        'train_stop_gui',
                        'trains_gui',
                        'transport_belt_gui',
                        'turret_gui',
                        'upgrade_item_gui',
                        'wall_gui',
                    },
                },
                render_mode = {
                    other_fields = false,
                    fields = {
                        'chart',
                        'chart_zoomed_in',
                        'game',
                    },
                },
                rich_text_setting = {
                    other_fields = false,
                    fields = {
                        'disabled',
                        'enabled',
                        'highlight',
                    },
                },
                riding = {
                    other_fields = false,
                    fields = {
                        acceleration = {
                            other_fields = false,
                            fields = {
                                'accelerating',
                                'braking',
                                'nothing',
                                'reversing',
                            },
                        },
                        direction = {
                            other_fields = false,
                            fields = {
                                'left',
                                'right',
                                'straight',
                            },
                        },
                    },
                },
                robot_order_type = {
                    other_fields = false,
                    fields = {
                        'construct',
                        'deconstruct',
                        'deliver',
                        'deliver_items',
                        'explode_cliff',
                        'pickup',
                        'pickup_items',
                        'repair',
                        'upgrade',
                    },
                },
                rocket_silo_status = {
                    other_fields = false,
                    fields = {
                        'arms_advance',
                        'arms_retract',
                        'building_rocket',
                        'create_rocket',
                        'doors_closing',
                        'doors_opened',
                        'doors_opening',
                        'engine_starting',
                        'launch_started',
                        'launch_starting',
                        'lights_blinking_close',
                        'lights_blinking_open',
                        'rocket_flying',
                        'rocket_ready',
                        'rocket_rising',
                    },
                },
                selection_mode = {
                    other_fields = false,
                    fields = {
                        'alt_reverse_select',
                        'alt_select',
                        'reverse_select',
                        'select',
                    },
                },
                shooting = {
                    other_fields = false,
                    fields = {
                        'not_shooting',
                        'shooting_enemies',
                        'shooting_selected',
                    },
                },
                signal_state = {
                    other_fields = false,
                    fields = {
                        'closed',
                        'open',
                        'reserved',
                        'reserved_by_circuit_network',
                    },
                },
                space_platform_state = {
                    other_fields = false,
                    fields = {
                        'no_path',
                        'no_schedule',
                        'on_the_path',
                        'paused',
                        'starter_pack_on_the_way',
                        'starter_pack_requested',
                        'waiting_at_station',
                        'waiting_for_departure',
                        'waiting_for_starter_pack',
                    },
                },
                target_type = {
                    other_fields = false,
                    fields = {
                        'cargo_hatch',
                        'commandable',
                        'custom_chart_tag',
                        'entity',
                        'equipment',
                        'equipment_grid',
                        'gui_element',
                        'item',
                        'logistic_cell',
                        'logistic_network',
                        'logistic_section',
                        'permission_group',
                        'planet',
                        'player',
                        'rail_path',
                        'render_object',
                        'space_platform',
                        'surface',
                        'train',
                    },
                },
                train_state = {
                    other_fields = false,
                    fields = {
                        'arrive_signal',
                        'arrive_station',
                        'destination_full',
                        'manual_control',
                        'manual_control_stop',
                        'no_path',
                        'no_schedule',
                        'on_the_path',
                        'wait_signal',
                        'wait_station',
                    },
                },
                transport_line = {
                    other_fields = false,
                    fields = {
                        'left_line',
                        'left_split_line',
                        'left_underground_line',
                        'right_line',
                        'right_split_line',
                        'right_underground_line',
                        'secondary_left_line',
                        'secondary_left_split_line',
                        'secondary_right_line',
                        'secondary_right_split_line',
                    },
                },
                wire_connector_id = {
                    other_fields = false,
                    fields = {
                        'circuit_green',
                        'circuit_red',
                        'combinator_input_green',
                        'combinator_input_red',
                        'combinator_output_green',
                        'combinator_output_red',
                        'pole_copper',
                        'power_switch_left_copper',
                        'power_switch_right_copper',
                    },
                },
                wire_origin = {
                    other_fields = false,
                    fields = {
                        'player',
                        'radars',
                        'script',
                    },
                },
                wire_type = {
                    other_fields = false,
                    fields = {
                        'copper',
                        'green',
                        'red',
                    },
                },
            },
        },
    },
}

stds.factorio_data = {
    read_globals = {
        data = {
            fields = {
                raw = {
                    other_fields = true,
                    read_only = false,
                },
                'extend',
                'is_demo',
            },
        },
        settings = {
            fields = {
                'startup',
                'global',
                'player',
            },
        },
        mods = {
            other_fields = true,
        },
    },
}

stds.factorio_control = {
    read_globals = {
        game = {
            other_fields = false,
            read_only = false,
            fields = {
                'auto_save',
                'ban_player',
                'check_consistency',
                'console_command_used',
                'create_force',
                'create_inventory',
                'create_profiler',
                'create_random_generator',
                'create_surface',
                'delete_surface',
                'difficulty',
                'disable_replay',
                'finished_but_continuing',
                'finished',
                'force_crc',
                'get_entity_by_tag',
                'get_entity_by_unit_number',
                'get_map_exchange_string',
                'get_player',
                'get_pollution_statistics',
                'get_script_inventories',
                'get_surfaces',
                'get_vehicles',
                'is_demo',
                'is_multiplayer',
                'kick_player',
                'merge_forces',
                'mute_player',
                'object_name',
                'play_sound',
                'print',
                'purge_player',
                'regenerate_entity',
                'reload_mods',
                'reload_script',
                'remove_offline_players',
                'reset_game_state',
                'reset_time_played',
                'save_atlas',
                'server_save',
                'set_game_state',
                'set_wait_for_screenshot_to_finish',
                'set_win_ending_info',
                'show_message_dialog',
                'take_screenshot',
                'take_technology_screenshot',
                'tick',
                'ticks_played',
                'unban_player',
                'unmute_player',
                allow_tip_activation = { read_only = false, other_fields = false },
                autosave_enabled = { read_only = false, other_fields = false },
                backer_names = { read_only = true, other_fields = true },
                blueprints = { read_only = true, other_fields = true },
                connected_players = { read_only = true, other_fields = true },
                default_map_gen_settings = { read_only = true, other_fields = true },
                difficulty_settings = { read_only = true, other_fields = true },
                draw_resource_selection = { read_only = false, other_fields = false },
                enemy_has_vision_on_land_mines = { read_only = false, other_fields = false },
                forces = { read_only = true, other_fields = true },
                map_settings = { read_only = true, other_fields = true },
                permissions = { read_only = true, other_fields = true },
                planets = { read_only = true, other_fields = true },
                player = { read_only = true, other_fields = true },
                players = { read_only = true, other_fields = true },
                simulation = { read_only = true, other_fields = true },
                speed = { read_only = false, other_fields = false },
                surfaces = { read_only = true, other_fields = true },
                technology_notifications_enabled = { read_only = false, other_fields = false },
                tick_paused = { read_only = false, other_fields = false },
                ticks_to_run = { read_only = false, other_fields = false },
                train_manager = { read_only = true, other_fields = true },
            },
        },
        script = {
            other_fields = false,
            fields = {
                active_mods = { other_fields = true, read_only = true },
                feature_flags = {
                    quality = { other_fields = false, read_only = true },
                    rail_bridges = { other_fields = false, read_only = true },
                    space_travel = { other_fields = false, read_only = true },
                    spoiling = { other_fields = false, read_only = true },
                    freezing = { other_fields = false, read_only = true },
                    segmented_units = { other_fields = false, read_only = true },
                    expansion_shaders = { other_fields = false, read_only = true },
                },
                generate_event_name = { other_fields = false, read_only = true },
                get_event_filter = { other_fields = false, read_only = true },
                get_event_handler = { other_fields = false, read_only = true },
                get_event_id = { other_fields = false, read_only = true },
                get_event_order = { other_fields = false, read_only = true },
                level = {
                    is_simulation = { other_fields = false, read_only = true },
                    is_tutorial = { other_fields = false, read_only = true },
                    campaign_name = { other_fields = false, read_only = true },
                    level_name = { other_fields = false, read_only = true },
                    mod_name = { other_fields = false, read_only = true },
                },
                mod_name = { other_fields = false, read_only = true },
                object_name = { other_fields = false, read_only = true },
                on_configuration_changed = { other_fields = false, read_only = true },
                on_event = { other_fields = false, read_only = true },
                on_init = { other_fields = false, read_only = true },
                on_load = { other_fields = false, read_only = true },
                on_nth_tick = { other_fields = false, read_only = true },
                raise_biter_base_built = { other_fields = false, read_only = true },
                raise_console_chat = { other_fields = false, read_only = true },
                raise_event = { other_fields = false, read_only = true },
                raise_market_item_purchased = { other_fields = false, read_only = true },
                raise_player_crafted_item = { other_fields = false, read_only = true },
                raise_player_fast_transferred = { other_fields = false, read_only = true },
                raise_script_built = { other_fields = false, read_only = true },
                raise_script_destroy = { other_fields = false, read_only = true },
                raise_script_revive = { other_fields = false, read_only = true },
                raise_script_set_tiles = { other_fields = false, read_only = true },
                raise_script_teleported = { other_fields = false, read_only = true },
                register_metatable = { other_fields = false, read_only = true },
                register_on_object_destroyed = { other_fields = false, read_only = true },
                set_event_filter = { other_fields = false, read_only = true },
            },
        },
        commands = {
            other_fields = false,
            fields = {
                'add_command',
                'remove_command',
                'commands',
                'game_commands',
                'object_name',
            },
        },
        helpers = {
            other_fields = false,
            fields = {
                'check_prototype_translations',
                'create_profiler',
                'decode_string',
                'direction_to_string',
                'encode_string',
                'evaluate_expression',
                'is_valid_sound_path',
                'is_valid_sprite_path',
                'json_to_table',
                'object_name',
                'parse_map_exchange_string',
                'remove_path',
                'table_to_json',
                'write_file',
            },
        },
        prototypes = {
            other_fields = false,
            fields = {
                'get_achievement_filtered',
                'get_decorative_filtered',
                'get_entity_filtered',
                'get_equipment_filtered',
                'get_fluid_filtered',
                'get_history',
                'get_item_filtered',
                'get_mod_setting_filtered',
                'get_recipe_filtered',
                'get_technology_filtered',
                'get_tile_filtered',
                achievement = { read_only = true, other_fields = true },
                active_trigger = { read_only = true, other_fields = true },
                airborne_pollutant = { read_only = true, other_fields = true },
                ammo_category = { read_only = true, other_fields = true },
                asteroid_chunk = { read_only = true, other_fields = true },
                autoplace_control = { read_only = true, other_fields = true },
                burner_usage = { read_only = true, other_fields = true },
                collision_layer = { read_only = true, other_fields = true },
                custom_event = { read_only = true, other_fields = true },
                custom_input = { read_only = true, other_fields = true },
                damage = { read_only = true, other_fields = true },
                decorative = { read_only = true, other_fields = true },
                entity = { read_only = true, other_fields = true },
                equipment = { read_only = true, other_fields = true },
                equipment_category = { read_only = true, other_fields = true },
                equipment_grid = { read_only = true, other_fields = true },
                fluid = { read_only = true, other_fields = true },
                font = { read_only = true, other_fields = true },
                fuel_category = { read_only = true, other_fields = true },
                item = { read_only = true, other_fields = true },
                item_group = { read_only = true, other_fields = true },
                item_subgroup = { read_only = true, other_fields = true },
                map_gen_preset = { read_only = true, other_fields = true },
                mod_setting = { read_only = true, other_fields = true },
                module_category = { read_only = true, other_fields = true },
                named_noise_expression = { read_only = true, other_fields = true },
                named_noise_function = { read_only = true, other_fields = true },
                particle = { read_only = true, other_fields = true },
                procession = { read_only = true, other_fields = true },
                procession_layer_inheritance_group = { read_only = true, other_fields = true },
                quality = { read_only = true, other_fields = true },
                recipe_category = { read_only = true, other_fields = true },
                resource_category = { read_only = true, other_fields = true },
                shortcut = { read_only = true, other_fields = true },
                space_connection = { read_only = true, other_fields = true },
                space_location = { read_only = true, other_fields = true },
                style = { read_only = true, other_fields = true },
                surface = { read_only = true, other_fields = true },
                surface_property = { read_only = true, other_fields = true },
                technology = { read_only = true, other_fields = true },
                tile = { read_only = true, other_fields = true },
                trivial_smoke = { read_only = true, other_fields = true },
                virtual_signal = { read_only = true, other_fields = true },
                'max_beacon_supply_area_distance',
                'max_electric_pole_connection_distance',
                'max_electric_pole_supply_area_distance',
                'max_force_distraction_chunk_distance',
                'max_force_distraction_distance',
                'max_gate_activation_distance',
                'max_inserter_reach_distance',
                'max_pipe_to_ground_distance',
                'max_underground_belt_distance',
            },
        },
        rcon = {
            other_fields = false,
            fields = { 'print', 'object_name' },
        },
        remote = {
            other_fields = false,
            fields = {
                'add_interface',
                'call',
                'object_name',
                'remove_interface',
                interfaces = { read_only = false, other_fields = true },
            },
        },
        rendering = {
            other_fields = false,
            fields = {
                'draw_line',
                'draw_text',
                'draw_circle',
                'draw_rectangle',
                'draw_arc',
                'draw_polygon',
                'draw_sprite',
                'draw_light',
                'draw_animation',
                'get_all_objects',
                'clear',
                'get_object_by_id',
                'object_name',
            },
        },
        settings = {
            fields = {
                'get_player_settings',
                'object_name',
                global = { read_only = false, other_fields = true },
                player_default = { read_only = false, other_fields = true },
                startup = { read_only = false, other_fields = true },
            },
        },
    },
    globals = {
        'storage',
    },
}

-- == WARNINGS ================================================================

--[[
    011 	A syntax error.
    021 	An invalid inline option.
    022 	An unpaired inline push directive.
    023 	An unpaired inline pop directive.
    111 	Setting an undefined global variable.
    112 	Mutating an undefined global variable.
    113 	Accessing an undefined global variable.
    121 	Setting a read-only global variable.
    122 	Setting a read-only field of a global variable.
    131 	Unused implicitly defined global variable.
    142 	Setting an undefined field of a global variable.
    143 	Accessing an undefined field of a global variable.
    211 	Unused local variable.
    212 	Unused argument.
    213 	Unused loop variable.
    214 	Used variable.
    221 	Local variable is accessed but never set.
    231 	Local variable is set but never accessed.
    232 	An argument is set but never accessed.
    233 	Loop variable is set but never accessed.
    241 	Local variable is mutated but never accessed.
    311 	Value assigned to a local variable is unused.
    312 	Value of an argument is unused.
    313 	Value of a loop variable is unused.
    314 	Value of a field in a table literal is unused.
    321 	Accessing uninitialized local variable.
    331 	Value assigned to a local variable is mutated but never accessed.
    341 	Mutating uninitialized local variable.
    411 	Redefining a local variable.
    412 	Redefining an argument.
    413 	Redefining a loop variable.
    421 	Shadowing a local variable.
    422 	Shadowing an argument.
    423 	Shadowing a loop variable.
    431 	Shadowing an upvalue.
    432 	Shadowing an upvalue argument.
    433 	Shadowing an upvalue loop variable.
    511 	Unreachable code.
    512 	Loop can be executed at most once.
    521 	Unused label.
    531 	Left-hand side of an assignment is too short.
    532 	Left-hand side of an assignment is too long.
    541 	An empty do end block.
    542 	An empty if branch.
    551 	An empty statement.
    561 	Cyclomatic complexity of a function is too high.
    571 	A numeric for loop goes from #(expr) down to 1 or less without negative step.
    581 	Negation of a relational operator- operator can be flipped.
    582 	Error prone negation: negation has a higher priority than equality.
    611 	A line consists of nothing but whitespace.
    612 	A line contains trailing whitespace.
    613 	Trailing whitespace in a string.
    614 	Trailing whitespace in a comment.
    621 	Inconsistent indentation (SPACE followed by TAB).
    631 	Line is too long.
]]