return {
    force_name_map = {
        player = 'Spectator',
        north = 'West',
        south = 'East'
    },
    game_state = {
        initializing = 0,
        picking      = 1,
        preparing    = 2,
        playing      = 3,
        finished     = 4,
        resetting    = 5,
    },
    permission_group = {
        admin   = 'admin',
        default = 'default',
        jail    = 'jail',
        player  = 'player',
    },
    spawn_point = {
        player = { x =    0, y = 0 },
        north  = { x = -320, y = 0 },
        south  = { x =  320, y = 0 },
    },
    color = {
        north = { 140, 140, 252 },
        south = { 252, 084, 084 },
        player = {111, 111, 111 },
    },
    challenges = {
        { caption = 'Lab Rush', tooltip = 'Place a total of 100 labs.' },
        { caption = 'Fish Catcher', tooltip = 'Use an inserter to catch a fish.' },
        { caption = 'Light Up!', tooltip = 'Place 3 lamps.' },
        { caption = 'Gone Fishing', tooltip = 'Collect 100 fish.' },
        { caption = 'Botlap', tooltip = 'Place the first locomotive by bots within 90mins' },
        { caption = 'Acid Storage', tooltip = 'Fill 100 barrels with sulfuric acid.' },
        { caption = 'Uranium Touch', tooltip = 'Craft a single U-235.' },
        { caption = 'Armoured Up', tooltip = 'Fill the equipment grid of a modular armor.' },
        { caption = 'Lab Speedster', tooltip = 'Research Lab Speed 3 technology.' },
        { caption = 'Blue Chip', tooltip = 'Craft a Processing Unit.' },
        { caption = 'LDS Factory', tooltip = 'Craft a Low-Density Structure.' },
        { caption = 'Rocket Fuel!', tooltip = 'Craft a Rocket Fuel item.' },
        { caption = 'Solaris', tooltip = 'Place and draw power from 100 solar panels.' },
        { caption = 'Delivery Master', tooltip = 'Deliver 10,000 items via logistic robots.' },
        { caption = 'Boom!', tooltip = 'Explode a cliff using explosives.' },
        { caption = 'RIP', tooltip = 'Die once in any way.' },
        { caption = 'Railscaper', tooltip = 'Construct a rail loop that fully surrounds your starter lake and complete 5 laps in a train.' },
        { caption = 'Module Mixer', tooltip = 'Insert 3 different tier 2 modules into a single machine.' },
        { caption = 'Laser Defense', tooltip = 'Craft and equip a Personal Laser Defense.' },
        { caption = 'Sommelier', tooltip = 'Have at least one of every barrel type in your inventory.' },
        { caption = 'Coal Hoarder', tooltip = 'Fill your entire inventory with coal and nothing else.' },
        { caption = 'Many Hands', tooltip = 'Possess one of every type of inserter.' },
        { caption = 'Pyromaniac', tooltip = 'Set something on fire.' },
        { caption = 'Pissed off', tooltip = 'Craft 1 bottle of utility science.' },
        { caption = 'Chestplosion', tooltip = 'Cause a chestplosion that fully covers a stone patch (no other entities allowed).' },
        { caption = 'Crash Test', tooltip = 'Destroy a car completely by crashing it into obstacles.' },
        { caption = 'Mining Boost', tooltip = 'Research Mining Productivity 1 technology.' },
        { caption = 'Logic Mastery', tooltip = 'Place one of every combinator type.' },
        { caption = 'Roadkill', tooltip = 'Die by getting run over by a car or tank.' },
        { caption = 'Lube up', tooltip = 'Completely fill a fluid wagon with lubricant.' },
        { caption = 'Paint It Red', tooltip = 'Gather 10,000 copper ore.' },
        { caption = 'Pole Wrecker', tooltip = 'Destroy 200 power poles.' },
        { caption = 'Chip Maker', tooltip = 'Craft 100 red circuits.' },
        { caption = 'Green Factory', tooltip = 'Craft 1,000 green circuits.' },
        { caption = 'Steel Axe', tooltip = 'Unlock the Steel Axe technology.' },
        { caption = 'Fortified!', tooltip = 'Surround yourself with 8 walls in a square.' },
        { caption = 'Shotgun Lord', tooltip = 'Craft 50 shotguns.' },
        { caption = 'Max Mining', tooltip = 'Cover every tile of a coal patch with mining drills without overlap.' },
        { caption = 'Beacon King', tooltip = 'Have 12 machines running under the influence of a single beacon.' },
        { caption = 'Belt Mastery', tooltip = 'Craft and equip a Belt Immunity Equipment.' },
        { caption = 'Red Supremacy', tooltip = 'Craft 200 Fast Underground Belts.' },
        { caption = 'Bulk Inserter', tooltip = 'Craft 200 Bulk Inserters.' },
        { caption = 'Ironception', tooltip = 'Fill an iron chest with iron chests.' },
        { caption = 'Battery Test', tooltip = 'Fully charge and discharge an accumulator.' },
        { caption = 'Piping Madness', tooltip = 'Place a water pump on every usable tile of your starter lake and connect them all with pipes.' },
        { caption = 'Manual Teardown', tooltip = 'Deconstruct a fully built smelter setup by hand.' },
        { caption = 'Copper Pavement', tooltip = 'Completely cover a copper patch with stone bricks.' },
        { caption = 'Belt Loop Ride', tooltip = 'Stand on a 4-tile circular belt loop for 1 minute without moving manually.' },
        { caption = 'Radar Network', tooltip = 'Place and power 50 radars at full energy satisfaction.' },
        { caption = 'Long Haul', tooltip = 'Construct a train with at least 10 wagons.' },
        { caption = 'Steel Upgrade', tooltip = 'Upgrade all furnaces to steel furnaces (without deconstructing everything first).' },
        { caption = 'Rock Solid Connection', tooltip = 'Connect your power network to 20 rocks.' },
        { caption = 'Landfill Filler', tooltip = 'Place 200 landfill tiles.' },
        { caption = 'Turret Buster', tooltip = 'Destroy a Gun Turret.' },
        { caption = 'Inventory Variety', tooltip = 'Fill your inventory with a different item in every slot.' },
        { caption = 'Belt Loop Adventure', tooltip = 'Ride a belt loop around your starter lake.' },
        --{ caption = 'Steelworks', tooltip = 'Produce 100 steel plates.' },
        --{ caption = 'Fusion Core', tooltip = 'Equip a Portable Fusion Reactor in your armor.' },

        { caption = 'Red Ammo Belt', tooltip = 'Fill a belt loop with 500 rounds of Piercing rounds magazines.' },
        { caption = 'Heart-Shaped Box', tooltip = 'Place 200 wooden chests in a heart shape.' },
        { caption = 'Power Waster', tooltip = 'Use over 100 MW for 1 full minute.' },
        { caption = 'Racer', tooltip = 'Stay in a car for 3 minutes without exiting.' },
        { caption = 'Display of Affection', tooltip = 'Write “I❤️FACTORIO” using 10 display panels.' },
        { caption = 'The Ground Is Lava', tooltip = 'Produce at least 1,000 concrete and walk only on it for 1 minute.' },
        { caption = 'Burner Metropolis', tooltip = 'Place 200 burner mining drills.' },
        { caption = 'Oil Explorer', tooltip = 'Place 40 pumpjacks.' },
        { caption = 'Gatekeeper', tooltip = 'Build one gate that\'s 250 tiles long.' },
        { caption = 'Bug Check', tooltip = 'Destroy 1 biter base.' },
        { caption = 'Biter Extinction', tooltip = 'Destroy 25 biter bases.' },
        { caption = 'Catch Me If You Can', tooltip = 'Get chased by 100 biters at once.' },
        { caption = 'Shotgun Sheriff', tooltip = 'Kill 100 biters with only a shotgun.' },
        { caption = 'POWER IS FINE', tooltip = 'Total 5 min of yellow power, after researching "Electric Energy Distribution 1".' },
        { caption = 'Pole Upgrade Program', tooltip = 'Replace all small poles with medium ones.' },
        { caption = 'Looping Louie', tooltip = 'Build 100 separate belt loops.' },
        { caption = 'Collector’s Chest', tooltip = 'Fill a steel chest with full stacks of different items.' },
        { caption = 'Bullet Specialist', tooltip = 'Research Projectile Damage 4 + Shooting Speed 4.' },
        { caption = 'Assembly Line Upgrade', tooltip = 'Upgrade all assemblers to level 2.' },
        { caption = 'Shooting Practice', tooltip = 'Use 500 yellow ammo on biters.' },
        { caption = 'Underground Pipe (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2000) underground pipes.' },
        { caption = 'Fast Inserter (Mega-Factory / Giga-Factory)', tooltip = 'Produce (500 / 1000) fast inserters.' },
        { caption = 'Rail (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2500 / 5000) rails.' },
        { caption = 'Big Electric Pole (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) big electric poles.' },
        { caption = 'Train Stop (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) train stops.' },
        { caption = 'Locomotive (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (10 / 25 / 50) locomotives.' },
        { caption = 'Fluid Wagon (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 50 / 100) fluid wagons.' },
        { caption = 'Car (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 50 / 150) cars.' },
        { caption = 'Refined Hazard Concrete (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2500 / 5000) refined hazard concrete.' },
        { caption = 'Accumulator (Mega-Factory / Giga-Factory)', tooltip = 'Produce (500 / 1000) accumulators.' },
        { caption = 'Module (Mega-Factory / Giga-Factory)', tooltip = 'Produce (150 / 300) modules.' },
        { caption = 'Flamethrower Turret (Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 75) flamethrower turrets.' },
        { caption = 'Rocket (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 3000) rockets.' },
        { caption = 'Land Mine (Mega-Factory / Giga-Factory)', tooltip = 'Produce (5000 / 10000) land mines.' },
        { caption = 'Flamethrower Ammo (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2000) flamethrower ammo.' },
        { caption = 'Grenade (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 500 / 1000) grenades.' },
        { caption = 'Defender Capsule (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) defender capsules.' },
        { caption = 'Submachine Gun (Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 300) submachine guns.' },
        { caption = 'Programmable Speaker (Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 750) programmable speakers.' },
        { caption = 'Fast Splitter (Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250) fast splitters.' },
        { caption = 'Electric Pump (Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 750) electric pumps.' },
        { caption = 'Oil Refinery (Mega-Factory / Giga-Factory)', tooltip = 'Produce (50 / 150) oil refineries.' },
        { caption = 'Solid Fuel (Mega-Factory / Giga-Factory)', tooltip = 'Produce (5000 / 10000) solid fuel.' },

    }    
}