return {
    force_name_map = {
        player = 'Spectator',
        north = 'West',
        south = 'East'
    },
    game_state = {
        initializing = 0,
        picking      = 1,
        preparing    = 2,
        playing      = 3,
        finished     = 4,
        resetting    = 5,
    },
    permission_group = {
        admin   = 'admin',
        default = 'default',
        jail    = 'jail',
        player  = 'player',
    },
    spawn_point = {
        player = { x =    0, y = 0 },
        north  = { x = -320, y = 0 },
        south  = { x =  320, y = 0 },
    },
    color = {
        north = { 140, 140, 252 },
        south = { 252, 084, 084 },
        player = {111, 111, 111 },
    },
    challenges = {
        { caption = 'Lab Rush', tooltip = 'Place 100 labs all running research.' },
        { caption = 'Fish Catcher', tooltip = 'Use an inserter to catch a fish.' },
        { caption = 'Light Up!', tooltip = 'Place 3 lamps.' },
        { caption = 'Fishing Industry', tooltip = 'Collect 200 fish.' },
        { caption = 'Botlap', tooltip = 'Place a locomotive with bots.' },
        { caption = 'Acid Barrels', tooltip = 'Fill 100 barrels with sulfuric acid.' },
        { caption = 'Uranium Touch', tooltip = 'Craft one U-235.' },
        { caption = 'Fully Equipped', tooltip = 'Fill the equipment grid of a modular armor.' },
        { caption = 'Blue Chips', tooltip = 'Craft 100 processing units.' },
        { caption = 'LDS Factory', tooltip = 'Craft 150 low-density structures.' },
        { caption = 'Rocket Fuel', tooltip = 'Craft 200 rocket fuel.' },
        { caption = 'Solaris', tooltip = 'Place and connect 100 solar panels.' },
        { caption = 'Delivery Service', tooltip = 'Deliver 10,000 items by logistic robots.' },
        { caption = 'Cliffhanger', tooltip = 'Destroy a cliff.' },
        { caption = 'RIP', tooltip = 'Die in any way.' },
        { caption = 'Rollercoaster', tooltip = 'Build a rail loop around your starter lake and complete 5 train laps.' },
        { caption = 'Rainbow Barrels', tooltip = 'Carry one of each barrel type.' },
        { caption = 'Coal Hoarder', tooltip = 'Fill your inventory with coal only.' },
        { caption = 'Inserter Collector', tooltip = 'Hold one of every type of inserter.' },
        { caption = 'Pyromaniac', tooltip = 'Use a flamethrower.' },
        { caption = 'Chestplosion', tooltip = 'Cause a chestplosion that fully covers a stone patch.' },
        { caption = 'Crash Test', tooltip = 'Destroy a car completely by crashing it into obstacles.' },
        { caption = 'Productive Mining', tooltip = 'Unlock Mining Productivity 1.' },
        { caption = 'Lube Up', tooltip = 'Fully fill a fluid wagon with lubricant.' },
        { caption = 'Paint It Red', tooltip = 'Gather 10,000 copper ore.' },
        { caption = 'Pole Wrecker', tooltip = 'Destroy 200 power poles.' },
        { caption = 'Steel Axe', tooltip = 'Unlock the Steel Axe technology.' },
        { caption = 'Fortified!', tooltip = 'Wall yourself in with 8 tiles.' },
        { caption = 'Shotgun Lord', tooltip = 'Craft 50 shotguns.' },
        { caption = 'Perfect Mining', tooltip = 'Use electric mining drills to fully cover one coal patch without overlapping areas.' },
        { caption = 'Red Supremacy', tooltip = 'Craft 200 fast underground belts.' },
        { caption = 'Bulk Inserters', tooltip = 'Craft 200 bulk inserters.' },
        { caption = 'Ironception', tooltip = 'Fill an iron chest with iron chests.' },
        { caption = 'Accumulator Test', tooltip = 'Fully charge and discharge 500 accumulators.' },
        { caption = 'Pumped Dry', tooltip = 'Place pumps on every usable position of your starter lake and connect their outputs.' },
        { caption = 'Copper Pavement', tooltip = 'Cover a copper patch with stone bricks.' },
        { caption = 'Radar Network', tooltip = 'Power 50 radars at full energy satisfaction.' },
        { caption = 'Freight Train', tooltip = 'Construct a train with 10 wagons.' },
        { caption = 'Steel Upgrade', tooltip = 'Upgrade 150 furnaces to steel furnaces.' },
        { caption = 'Rock and Stone!', tooltip = 'Connect power to 20 rocks.' },
        { caption = 'Landfiller', tooltip = 'Place 200 landfill.' },
        { caption = 'Turret Buster', tooltip = 'Destroy one gun turret.' },
        { caption = 'Inventory Variety', tooltip = 'Fill your inventory with a different item in every slot.' },
        { caption = 'Belt Loop Adventure', tooltip = 'Ride a belt loop around your starter lake.' },
        { caption = 'Scenic Belt Loop', tooltip = 'Ride a belt loop around your starter lake without moving manually.' },
        { caption = 'Red Ammo Belt', tooltip = 'Fill a belt loop with 500 rounds of Piercing rounds magazines.' },
        { caption = 'Heart-Shaped Box', tooltip = 'Place 200 wooden chests in a heart shape.' },
        { caption = 'Power Waster', tooltip = 'Use over 100 MW for 1 full minute.' },
        { caption = 'Racer', tooltip = 'Stay in a car for 3 minutes without exiting.' },
        { caption = 'Display of Affection', tooltip = 'Write “I❤️FACTORIO” using 10 display panels.' },
        { caption = 'The Ground Is Lava', tooltip = 'Produce at least 1,000 concrete and walk only on it for 1 minute.' },
        { caption = 'Burner Metropolis', tooltip = 'Place 200 burner mining drills.' },
        { caption = 'Oil Explorer', tooltip = 'Place 40 pumpjacks.' },
        { caption = 'Gatekeeper', tooltip = 'Build one gate that\'s 250 tiles long.' },
        { caption = 'Bug Check', tooltip = 'Destroy 1 biter base.' },
        { caption = 'Biter Extinction', tooltip = 'Destroy 25 biter bases.' },
        { caption = 'Catch Me If You Can', tooltip = 'Get chased by 100 biters at once.' },
        { caption = 'Shotgun Sheriff', tooltip = 'Kill 100 biters with only a shotgun.' },
        { caption = 'POWER IS FINE', tooltip = 'Total 5 min of yellow power, after researching "Electric Energy Distribution 1".' },
        { caption = 'Pole Upgrade Program', tooltip = 'Replace all small poles with medium ones.' },
        { caption = 'Looping Louie', tooltip = 'Build 100 separate belt loops.' },
        { caption = 'Collector’s Chest', tooltip = 'Fill a steel chest with full stacks of different items.' },
        { caption = 'Bullet Specialist', tooltip = 'Research Projectile Damage 4 + Shooting Speed 4.' },
        { caption = 'Assembly Line Upgrade', tooltip = 'Upgrade all assemblers to level 2.' },
        { caption = 'Shooting Practice', tooltip = 'Use 500 yellow ammo on biters.' },
        { caption = 'Underground Pipe (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2000) underground pipes.' },
        { caption = 'Fast Inserter (Mega-Factory / Giga-Factory)', tooltip = 'Produce (500 / 1000) fast inserters.' },
        { caption = 'Rail (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2500 / 5000) rails.' },
        { caption = 'Big Electric Pole (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) big electric poles.' },
        { caption = 'Train Stop (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) train stops.' },
        { caption = 'Locomotive (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (10 / 25 / 50) locomotives.' },
        { caption = 'Fluid Wagon (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 50 / 100) fluid wagons.' },
        { caption = 'Car (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 50 / 150) cars.' },
        { caption = 'Refined Hazard Concrete (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2500 / 5000) refined hazard concrete.' },
        { caption = 'Accumulator (Mega-Factory / Giga-Factory)', tooltip = 'Produce (500 / 1000) accumulators.' },
        { caption = 'Module (Mega-Factory / Giga-Factory)', tooltip = 'Produce (150 / 300) modules.' },
        { caption = 'Flamethrower Turret (Mega-Factory / Giga-Factory)', tooltip = 'Produce (25 / 75) flamethrower turrets.' },
        { caption = 'Rocket (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 3000) rockets.' },
        { caption = 'Land Mine (Mega-Factory / Giga-Factory)', tooltip = 'Produce (5000 / 10000) land mines.' },
        { caption = 'Flamethrower Ammo (Mega-Factory / Giga-Factory)', tooltip = 'Produce (1000 / 2000) flamethrower ammo.' },
        { caption = 'Grenade (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 500 / 1000) grenades.' },
        { caption = 'Defender Capsule (Factory / Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250 / 500) defender capsules.' },
        { caption = 'Submachine Gun (Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 300) submachine guns.' },
        { caption = 'Programmable Speaker (Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 750) programmable speakers.' },
        { caption = 'Fast Splitter (Mega-Factory / Giga-Factory)', tooltip = 'Produce (100 / 250) fast splitters.' },
        { caption = 'Electric Pump (Mega-Factory / Giga-Factory)', tooltip = 'Produce (250 / 750) electric pumps.' },
        { caption = 'Oil Refinery (Mega-Factory / Giga-Factory)', tooltip = 'Produce (50 / 150) oil refineries.' },
        { caption = 'Solid Fuel (Mega-Factory / Giga-Factory)', tooltip = 'Produce (5000 / 10000) solid fuel.' },
    }
}