return {
    force_name_map = {
        player = 'Spectator',
        north = 'West',
        south = 'East'
    },
    game_state = {
        initializing = 0,
        picking      = 1,
        preparing    = 2,
        playing      = 3,
        finished     = 4,
        resetting    = 5,
    },
    permission_group = {
        admin   = 'admin',
        default = 'default',
        jail    = 'jail',
        player  = 'player',
    },
    spawn_point = {
        player = { x =    0, y = 0 },
        north  = { x = -320, y = 0 },
        south  = { x =  320, y = 0 },
    },
    color = {
        north = { 140, 140, 252 },
        south = { 252, 084, 084 },
        player = {111, 111, 111 },
    },
    challenges = {
        { caption = 'Lab Rush', tooltip = 'Place a total of 100 labs.' },
        { caption = 'Fish Catcher', tooltip = 'Use an inserter to catch a fish.' },
        { caption = 'Light Up!', tooltip = 'Place 3 lamps.' },
        { caption = 'Gone Fishing', tooltip = 'Collect 100 fish.' },
        { caption = 'Botlap', tooltip = 'Place the first locomotive by bots within 90mins' },
        { caption = 'Acid Storage', tooltip = 'Fill 100 barrels with sulfuric acid.' },
        { caption = 'Uranium Touch', tooltip = 'Craft a single U-235.' },
        { caption = 'Armoured Up', tooltip = 'Fill the equipment grid of a modular armor.' },
        { caption = 'Lab Speedster', tooltip = 'Research Lab Speed 3 technology.' },
        { caption = 'Blue Chip', tooltip = 'Craft a Processing Unit.' },
        { caption = 'LDS Factory', tooltip = 'Craft a Low-Density Structure.' },
        { caption = 'Rocket Fuel!', tooltip = 'Craft a Rocket Fuel item.' },
        { caption = 'Solaris', tooltip = 'Place and draw power from 100 solar panels.' },
        { caption = 'Delivery Master', tooltip = 'Deliver 10,000 items via logistic robots.' },
        { caption = 'Boom!', tooltip = 'Explode a cliff using explosives.' },
        { caption = 'RIP', tooltip = 'Die once in any way.' },
        { caption = 'Railscaper', tooltip = 'Construct a rail loop that fully surrounds your starter lake and complete 5 laps in a train.' },
        { caption = 'Module Mixer', tooltip = 'Insert 3 different tier 2 modules into a single machine.' },
        { caption = 'Laser Defense', tooltip = 'Craft and equip a Personal Laser Defense.' },
        { caption = 'Sommelier', tooltip = 'Have at least one of every barrel type in your inventory.' },
        { caption = 'Coal Hoarder', tooltip = 'Fill your entire inventory with coal and nothing else.' },
        { caption = 'Many Hands', tooltip = 'Possess one of every type of inserter.' },
        { caption = 'Pyromaniac', tooltip = 'Set something on fire.' },
        { caption = 'Pissed off', tooltip = 'Craft 1 bottle of utility science.' },
        { caption = 'Chestplosion', tooltip = 'Cause a chestplosion that fully covers a stone patch (no other entities allowed).' },
        { caption = 'Crash Test', tooltip = 'Destroy a car completely by crashing it into obstacles.' },
        { caption = 'Mining Boost', tooltip = 'Research Mining Productivity 1 technology.' },
        { caption = 'Logic Mastery', tooltip = 'Place one of every combinator type.' },
        { caption = 'Roadkill', tooltip = 'Die by getting run over by a car or tank.' },
        { caption = 'Lube up', tooltip = 'Completely fill a fluid wagon with lubricant.' },
        { caption = 'Paint It Red', tooltip = 'Gather 10,000 copper ore.' },
        { caption = 'Pole Wrecker', tooltip = 'Destroy 200 power poles.' },
        { caption = 'Chip Maker', tooltip = 'Craft 100 red circuits.' },
        { caption = 'Green Factory', tooltip = 'Craft 1,000 green circuits.' },
        { caption = 'Steel Axe', tooltip = 'Unlock the Steel Axe technology.' },
        { caption = 'Fortified!', tooltip = 'Surround yourself with 8 walls in a square.' },
        { caption = 'Shotgun Lord', tooltip = 'Craft 50 shotguns.' },
        { caption = 'Max Mining', tooltip = 'Cover every tile of a coal patch with mining drills without overlap.' },
        { caption = 'Beacon King', tooltip = 'Have 12 machines running under the influence of a single beacon.' },
        { caption = 'Belt Mastery', tooltip = 'Craft and equip a Belt Immunity Equipment.' },
        { caption = 'Red Supremacy', tooltip = 'Craft 200 Fast Underground Belts.' },
        { caption = 'Bulk Inserter', tooltip = 'Craft 200 Bulk Inserters.' },
        { caption = 'Ironception', tooltip = 'Fill an iron chest with iron chests.' },
        { caption = 'Battery Test', tooltip = 'Fully charge and discharge an accumulator.' },
        { caption = 'Piping Madness', tooltip = 'Place a water pump on every usable tile of your starter lake and connect them all with pipes.' },
        { caption = 'Manual Teardown', tooltip = 'Deconstruct a fully built smelter setup by hand.' },
        { caption = 'Copper Pavement', tooltip = 'Completely cover a copper patch with stone bricks.' },
        { caption = 'Belt Loop Ride', tooltip = 'Stand on a 4-tile circular belt loop for 1 minute without moving manually.' },
        { caption = 'Radar Network', tooltip = 'Place and power 50 radars at full energy satisfaction.' },
        { caption = 'Long Haul', tooltip = 'Construct a train with at least 10 wagons.' },
        { caption = 'Steel Upgrade', tooltip = 'Upgrade all furnaces to steel furnaces (without deconstructing everything first).' },
        { caption = 'Rock Solid Connection', tooltip = 'Connect your power network to 20 rocks.' },
        { caption = 'Landfill Filler', tooltip = 'Place 200 landfill tiles.' },
        { caption = 'Turret Buster', tooltip = 'Destroy a Gun Turret.' },
        { caption = 'Inventory Variety', tooltip = 'Fill your inventory with a different item in every slot.' },
        { caption = 'Belt Loop Adventure', tooltip = 'Ride a belt loop around your starter lake.' },
        --{ caption = 'Steelworks', tooltip = 'Produce 100 steel plates.' },
        --{ caption = 'Fusion Core', tooltip = 'Equip a Portable Fusion Reactor in your armor.' },
    }    
}